FONT_FAMILY = "Arial"

SIZE_XS = 11
SIZE_SM = 12
SIZE_MD = 14
SIZE_LG = 18
SIZE_XL = 22
SIZE_2XL = 24

WEIGHT_REGULAR = "normal"
WEIGHT_BOLD = "bold"

TITLE = (FONT_FAMILY, SIZE_2XL, WEIGHT_BOLD)
HEADER_TITLE = (FONT_FAMILY, SIZE_XL, WEIGHT_BOLD)
SECTION_TITLE = (FONT_FAMILY, SIZE_LG, WEIGHT_BOLD)
BODY = (FONT_FAMILY, SIZE_MD)
BODY_BOLD = (FONT_FAMILY, SIZE_MD, WEIGHT_BOLD)
SMALL = (FONT_FAMILY, SIZE_SM)
SMALL_BOLD = (FONT_FAMILY, SIZE_SM, WEIGHT_BOLD)
BADGE = (FONT_FAMILY, SIZE_XS, WEIGHT_BOLD)
